BAB - Add explanations of assistants
zkSNACKs/WasabiWalletWebSite pull request #27
Opened 2024-02-14 11:12 UTC by CAnorbo

Fix for #12446

2024-02-14 11:22 UTC, MarnixCroes commented on wwwroot/buy-anything.html
> +                                <p>If you have a specific flight or hotel picked out and want to pay with Bitcoin, choose the Fast Travel Assistant to confirm your plans quickly.</p>
```suggestion
                                <p>If you have a specific flight or hotel picked out, choose the Fast Travel Assistant to confirm your plans quickly.</p>
```
no need to mention

2024-02-14 11:41 UTC, CAnorbo commented on wwwroot/buy-anything.html
> +                                <p>If you have a specific flight or hotel picked out and want to pay with Bitcoin, choose the Fast Travel Assistant to confirm your plans quickly.</p>
Fixed.

2024-02-26 18:20 UTC, yahiheb requested changes
LGTM, just a small nit.

2024-02-26 18:20 UTC, yahiheb commented on wwwroot/buy-anything.html
> +
```suggestion
```

2024-02-27 16:46 UTC, yahiheb requested changes

2024-02-27 16:46 UTC, yahiheb commented on wwwroot/buy-anything.html
> +                            <p>Wasabi Wallet is introducing an exciting feature in partnership with ShopinBit, enabling you to buy anything directly from your wallet using Bitcoin privately. No need
```suggestion
                            <p>Wasabi Wallet has introduced an exciting feature in partnership with ShopinBit, enabling you to buy anything directly from your wallet using Bitcoin privately. No need for exchanges or revealing personal information.</p>
```

2024-02-27 20:06 UTC, yahiheb approved these changes
LGTM

2024-02-28 09:33 UTC, adamPetho approved these changes
LGTM, any reason why this isn't merged in yet?

2024-02-28 12:25 UTC, CAnorbo commented
> LGTM, any reason why this isn't merged in yet?

There were some change requests, but it's ready to merge.

2024-02-28 12:26 UTC, merged